version: '3.8'
services:
  web:
    build: .
    ports:
      - "5177:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=notability_db
      - SECRET_KEY=your-secure-secret-key-here
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notability_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: