version: '3.8'
services:
  web:
    build: .
    restart: always
    ports:
      - "${PORT:-5177}:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-notability_db}
      - SECRET_KEY=${SECRET_KEY:-your-secure-secret-key-here}
    networks:
      - notability_network
    volumes:
      - pdf_data:/app/pdfs

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-notability_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notability_network

networks:
  notability_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  pdf_data:
    driver: local